spring.cloud.stream:
  function:
    definition: kafkaConsumer
  bindings:
    domainService-in-0:
      destination: KAFKA_CONSUMERS
  kafka:
    bindings:
      domainService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092